version: "3.5"

services:
  api01: &api
    build: .
    hostname: api01
    environment:
      DATABASE_URL: ecto://postgres:postgres@db:5432/crebito
      PORT: 4000
      RELEASE_NAME: "api1"
      RELEASE_NODE: "api1@127.0.0.1"
      RELEASE_DISTRIBUTION: "name"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '150MB'

  api02:
    # Essa sintaxe reusa o que foi declarado em 'api01'.
    <<: *api 
    hostname: api02
 
  nginx:
    image: nginx:latest
    restart: on-failure
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '50MB'

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=crebito
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/postgres.conf:/etc/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '200MB'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 10s
